import numpy as np

import pyroomacoustics as pra
from pyroomacoustics.directivities.harmonics import (
    get_mn_in_acn_order,
    real_sph_harm,
)


def test_harmonics_directivity():
    """
    Test the Room Impulse Response (RIR) generated by a set of microphones
    with real spherical harmonics directivities against the analytical values
    of the spherical harmonics.
    """
    order = 2
    condon_shortley_phase = False
    azimuth = np.deg2rad(50)

    room = pra.AnechoicRoom(fs=16000)
    room.add_source([np.cos(azimuth), np.sin(azimuth), 1.0])

    mm, nn = get_mn_in_acn_order(order)

    for m, n in zip(mm, nn):
        room.add_microphone(
            [0.0, 0.0, 1.0],
            directivity=pra.directivities.RealSphericalHarmonicsDirectivity(
                m, n, condon_shortley_phase=condon_shortley_phase
            ),
        )

    room.compute_rir()
    rir_sum = np.asarray(room.rir).squeeze().sum(axis=1)

    sh = real_sph_harm(
        nn, mm, np.pi / 2, azimuth, condon_shortley_phase=condon_shortley_phase
    )

    np.allclose(rir_sum, sh, atol=1e-2)
